### ISSUE TITLE
{"text":"Incorrect index","code":7,"invalid-event-number":1} - splunk-kubernetes-objects

### ISSUE THREAD

**Issue by vikeshbs** [splunk/splunk-connect-for-kubernetes#773] opened 2022-06-01 08:02 UTC
Hi,
I am seeing this error on the pod's logs for splunk-kubernetes-objects.

2022-06-01 07:55:39 +0000 [error]: #0 Fluent::Plugin::SplunkHecOutput: Failed POST to https://xx.xx.xx.xx:8088/services/collector, response: {"text":"Incorrect index","code":7,"invalid-event-number":1}
2022-06-01 07:55:44 +0000 [debug]: #0 [Sending] Chunk: 5e05e370bc6ce510af94b857bc9dec51(13699581B).
2022-06-01 07:55:44 +0000 [error]: #0 Failed POST to https://xx.xx.xx.xx:8088/services/collector, response: {"text":"Incorrect index","code":7,"invalid-event-number":1}

How to resolve this issue anyone?

Also if possible can someone share the sample values.yaml with the necessary configuration deployed in the K8s

**Comment by vinzent** [comment] 2022-06-01 08:24
funny this error is reported every few weeks - although the error message contains the root cause: `"text":"Incorrect index"`.  SCK is configured to log to send messages to an index that doesn't exist (or maybe the hec token has no access to).

maybe the error message sent from the splunk server could include the name of the inccorect index used. would help to identify the source (default from helm values.yaml, splunk.com/index namespace or pod annotation). but this is nothing SCK can do about. the error originates from the splunk server.

**Comment by vikeshbs** [comment] 2022-06-01 09:09
Thanks @vinzent, Issue resolved on this

**Comment by harshit-splunk** [comment] 2022-06-02 04:52
Closing the issue as it is resolved

**Closed by harshit-splunk** 2022-06-02 04:52 UTC
