### ISSUE TITLE
Splunk Connect App Issue On OpenShift

### ISSUE THREAD

**Issue by rajeshlparab** [splunk/splunk-connect-for-kubernetes#685] opened 2021-12-13 06:02 UTC
**What happened**:

We are using Splunk connect app to ship logs from OpenShift to Splunk

Currently, the metrics-related information is not reflected properly by this app. This behavior was confirmed by Eric (ericg@splunk.com) / Irshad (isiddiqi@splunk.com) from Splunk in their environment. 

**What you expected to happen**:
Metrics information is reported only from a single node and is not correct

**How to reproduce it (as minimally and precisely as possible)**:
It has been reproduced by your team Kevin/Irshad. Just run the app and check metrics information

**Anything else we need to know?**:

**Environment**:
•	Splunk version – (8.1.0)
•	OpenShift version – (4.7.9)
•	Kubernetes Version – (1.20)

We are planning to use this app for critical Deloitte project and need resolution at the earliest.
raparab@deloitte.com
kramula@deloitte.com

Debug log:
[my-splunk-connect-splunk-kubernetes-metrics-8pb7n-splunk-fluentd-k8s-metrics.log](https://github.com/splunk/splunk-connect-for-kubernetes/files/7701354/my-splunk-connect-splunk-kubernetes-metrics-8pb7n-splunk-fluentd-k8s-metrics.log)

config file:
[my_values_yaml.txt](https://github.com/splunk/splunk-connect-for-kubernetes/files/7701356/my_values_yaml.txt)

**Comment by rockb1017** [comment] 2021-12-14 21:25
the error is about SSL certification verification failure. 
could you try setting `splunk-kubernetes-metrics.kubernetes.insecureSSL` to `true`?

**Comment by matthewmodestino** [comment] 2021-12-15 21:18
Had them update to insecureSSL and now they seem to exhibit same issue as 

https://github.com/splunk/splunk-connect-for-kubernetes/issues/582

404 not found. Asking for full log dump.

**Comment by harshit-splunk** [comment] 2021-12-16 07:46
@matthewmodestino @rajeshlparab 

We have used below three endpoints in SCK connector for the metrics:

* /stats
* /stats/summary
* /metrics/cadvisor

From these, 'stats' also get data from 'cadvisor', but in JSON format. It seems that, starting 1.14/1.15, the cadvisor JSON APIs were being deprecated from kubelet. And, from 1.21, it was removed. So, the metrics plugin generated '404 not found' error for this endpoint, but others would work.

From the Github issue discussions, KEPs, pull-requests etc for 'k8s' repo, it seems that the remaining two endpoint would still be there, at least for some time, until a replacements are properly designed and implemented. So we just need to remove 'stats' endpoint and figure out how to get the metrics fetched from that endpoint using the new or alternative endpoints.

ref:
kubernetes/kubernetes#68522
kubernetes/enhancements#2130
kubernetes/kubernetes#78504

https://github.com/splunk/fluent-plugin-kubernetes-metrics/pull/102

**Comment by gnarc** [comment] 2021-12-16 10:28
Not sure this fits his problem:
1. in his values.yaml, insecureSSL: true is set
2. unless it has changed in OCP 4.7.x this is the output of failing to connect ot the /stats endpoint on some OCP 4.6.45 with 1.4.[7-10]:
```
2021-11-05 11:02:37 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2021-11-05 11:02:37 +0000 [info]: gem 'fluentd' version '1.14.2'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-jq' version '0.5.1'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-kubernetes-metrics' version '1.1.7'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.9.2'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-prometheus' version '2.0.2'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.1.0'
2021-11-05 11:02:37 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.7'
2021-11-05 11:02:41 +0000 [info]: Use URL https://10.0.1.107:10250/stats/summary for creating client to query kubelet summary api
2021-11-05 11:02:41 +0000 [info]: Use URL https://10.0.1.107:10250/stats for creating client to query kubelet stats api
2021-11-05 11:02:41 +0000 [info]: Use URL https://10.0.1.107:10250/metrics/cadvisor for creating client to query cadvisor metrics api
2021-11-05 11:02:41 +0000 [info]: using configuration file: <ROOT>
  <system>
    log_level info

[....] 
# the whole fluent config from the configmap
[...]
# finally a running worker and a failing stats_metric_scraper, who get detached but the rest will continue to work:

2021-11-05 11:02:50 +0000 [info]: #0 starting fluentd worker pid=12 ppid=1 worker=0
2021-11-05 11:02:50 +0000 [info]: #0 fluentd worker is now running worker=0

2021-11-05 11:03:07 +0000 [error]: #0 Unexpected error raised. Stopping the timer. title=:stats_metric_scraper error_class=RestClient::NotFound error="404 Not Found"
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/ruby/net/http.rb:933:in `start'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:233:in `_follow_redirection'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:145:in `follow_redirection'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:121:in `return!'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/ruby/net/http.rb:933:in `start'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
  2021-11-05 11:03:07 +0000 [error]: #0 /opt/app-root/src/gem/fluent-plugin-kubernetes-metrics-1.1.7/lib/fluent/plugin/in_kubernetes_metrics.rb:647:in `scrape_stats_metrics'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.14.2/lib/fluent/plugin_helper/timer.rb:80:in `on_timer'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run_once'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/cool.io-1.7.1/lib/cool.io/loop.rb:88:in `run'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.14.2/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2021-11-05 11:03:07 +0000 [error]: #0 /usr/share/gems/gems/fluentd-1.14.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2021-11-05 11:03:07 +0000 [error]: #0 Timer detached. title=:stats_metric_scraper

```

However in the OP's log all the scrapers (title=:metric_scraper , ...) are affected.

Another difference: In my setup the ConfigMap and therefore the fluent config in the metrics container's logs has multiple insecure_ssl lines which seems to be missing here.
I'd say if it is already missing in the related ConfigMap something must have gone wrong during installation/parsing the setting from the values.yaml into the helm template?

**Comment by matthewmodestino** [comment] 2021-12-16 12:22
The first post was caused by them not having `insecureSSL: true` set in the metrics kubernetes section. After working with them to clean that up, we not face the 404 on the missing endpoint.

@harshit-splunk do we know if we lose certain metrics due to this? should we be looking at moving the metrics to OTel collector instead?

**Comment by harshit-splunk** [comment] 2021-12-16 12:28
> @harshit-splunk do we know if we lose certain metrics due to this? should we be looking at moving the metrics to OTel collector instead?

We will loose all metric from `/stats` endpoimt (Complete list: https://github.com/splunk/fluent-plugin-kubernetes-metrics/blob/develop/metrics-information.md#stats-metrics )
As far as I know, sck-otel collects only collects from `/stats/summary` endpoint. It doesn't collect metric from `/stats` endpoint

**Comment by matthewmodestino** [comment] 2021-12-16 12:39
Got it, thanks! 

So TLDR, it will be expected that those metrics are no longer available, and we can advise customers it is expected when/if they contact support?

**Comment by harshit-splunk** [comment] 2021-12-16 12:42
> So TLDR, it will be expected that those metrics are no longer available, and we can advise customers it is expected when/if they contact support?

yes

**Comment by harshit-splunk** [comment] 2021-12-16 12:44
Some more info on this: https://github.com/kubernetes/kubernetes/issues/68522#issuecomment-724928827
"most metrics being removed should be available in the /metrics/cadvisor kubelet endpoint."

**Comment by matthewmodestino** [comment] 2021-12-16 12:45
Awesome, thanks @harshit-splunk!!

**Comment by harshit-splunk** [comment] 2021-12-23 12:10
@rajeshlparab @matthewmodestino should we close the issue?

**Comment by harshit-splunk** [comment] 2021-12-30 10:33
Closing for now. Feel free to reopen the issue if required.

**Closed by harshit-splunk** 2021-12-30 10:33 UTC
