### ISSUE TITLE
undefined method 'get_config_maps', 'get_component_statuses', 'get_persistent_volumes', 'get_resource_quotas' after adding these objects

### ISSUE THREAD

**Issue by davidxianggao** [splunk/splunk-connect-for-kubernetes#462] opened 2020-09-10 20:04 UTC
**What happened**:
 
I am getting errors in Splunk as followings, indicating some of the objects specified in the vaules.yaml file of splunk-kubernetes-objects can not be collected.

Some error entries/samples:

/usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing': undefined method `get_config_maps' for #<Kubeclient::Client:0x0000560142d50888> (NoMethodError)
/usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing': undefined method `get_component_statuses' for #<Kubeclient::Client:0x000055e6ce740670> (NoMethodError)
/usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing': undefined method `get_resource_quotas' for #<Kubeclient::Client:0x000055de1f585c48> (NoMethodError)
/usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing': undefined method `get_persistent_volumes' for #<Kubeclient::Client:0x000055de1f585c48> (NoMethodError)
...

**What you expected to happen**:

Some default core objects like pods, namespaces, nodes and events look good without any errors. Some newly-added objects like daemon_sets look good, at least no this "method_missing" error for daemon_sets either.

**How to reproduce it (as minimally and precisely as possible)**:

After a fresh vanilla helm deployment on splunk-kubernetes-objects, I've added additional objects in the values.yaml with the following:

objects:
...
...
  apps:
    v1:
      - name: component_statuses
      - name: config_maps
      - name: daemon_sets
      - name: deployments
      - name: persistent_volumes
      - name: persistent_volume_claims
      - name: replica_sets
      - name: resource_quotas
      - name: services
      - name: service_accounts
      - name: stateful_sets

**Anything else we need to know?**:

The objects currently in the values.yaml file of splunk-kubernetes-objects are:

objects:
   core:
     v1:
       - name: pods
       - name: namespaces
       - name: nodes
       - name: events
          mode: watch
   apps:
     v1:
       - name: component_statuses
       - name: config_maps
       - name: daemon_sets
       - name: deployments
       - name: persistent_volumes
       - name: persistent_volume_claims
       - name: replica_sets
       - name: resource_quotas
       - name: services
       - name: service_accounts
       - name: stateful_sets

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"4a1514f7dbb15bf5047b349d2599d23756ed75b8", GitTreeState:"clean", BuildDate:"2020-07-15T03:33:19Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- Ruby version (use `ruby --version`):
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Splunk version:
Splunk Enterprise
Version:
7.2.5.1
Build:
962d9a8e1586

- Others:

**Comment by schose** [comment] 2020-09-15 14:15
make sure to ask the correct api (core/v1, apps/v1...). here is a working example from me


```
splunk-kubernetes-objects:
  enabled: true
  objects:
    core:
      v1:
        - name: pods
        - name: namespaces
        - name: nodes
        - name: config_maps
        - name: persistent_volumes
        - name: component_statuses
        - name: service_accounts
        - name: events
          mode: watch
    apps:
      v1:
        - name: daemon_sets
        - name: deployments
```

as these settings are not well documented have a look at the logfile from the metrics daemonset.

e.g.:

```
/usr/share/gems/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing': undefined method `get_persistentvolume' for #<Kubeclient::Client:0x00005632d0e86120> (NoMethodError)
Did you mean?  get_persistent_volume
               get_persistent_volumes
```

in this case i needed to switch from persistentvolume to persistent_volumes

Regards,

Andreas

**Comment by davidxianggao** [comment] 2020-09-16 18:06
Thank you for your input and sharing, Schose. I've copied your object config into my Helm deployment but noticed that missing_method logging stopped since Sept. 13th (3 days ago). I didn't make any change since last week until yesterday of seeing your input. I will investigate more and try to figure it out.

**Comment by rockb1017** [comment] 2020-09-23 06:36
great to know that it is not complaining now. i couldn't reproduce it myself. I will close this for now.

**Closed by rockb1017** 2020-09-23 06:36 UTC
