### ISSUE TITLE
TOMCAT Container Logs not pushing to Splunk

### ISSUE THREAD

**Issue by jaypalpatil** [splunk/splunk-connect-for-kubernetes#573] opened 2021-03-01 16:50 UTC
**What happened**:
We have manually deployed the manifest file and not using the HELM option. Tomcat Container logs are not pushing to splunk but other containers logs are pushing to splunk. Other container logs path is '/var/logs' and path for tomcat logs is '/usr/local/tomcat/logs/erefill_*.log'. 

_Specifications of Tomcat Logs :_ 
- Logs Format - log4j
- Time Format - yyyy-MM-dd HH:mm:ss,SSS
- Regex - ^(\d{4}+\-\d+\-\d+ \d+:\d+:\d+,\d+)|(\[\d+\])|(\S+:\d+)|-|(\S+)|

**Tomcat Conf File**:
      
       `	tomcat.conf: |-
	<source>
	  @id tomcat.log
	  @type tail
	  @label @CONCAT
	  tag tail.containers.var.log.containers.toolbox*
	  path /usr/local/tomcat/logs/erefill_*.log
	  pos_file /var/log/tomcat.log.pos
	  path_key source
	  read_from_head true
	  refresh_interval 60
	  <parse>
		@type json
		time_format %Y-%m-%dT%H:%M:%S.%NZ
		time_key time
		time_type string
		localtime false
	  </parse>
	</source>`

**Filter for Tomcat Logs which is added in output.conf file :**

       `<filter tail.containers.var.log.containers.toolbox*toolbox*.log>
        @type concat
        key log
        timeout_label @SPLUNK
        stream_identity_key stream
        multiline_start_regexp /^(\d{4}+\-\d+\-\d+ \d+:\d+:\d+,\d+)|(\[\d+\])|(\S+:\d+)|-|(\S+)|
        multiline_end_regexp /\\n$/
        separator ""
        flush_interval 5s
      </filter>`

**Question/Doubts :**
1. Which parsing plugin should be used for log4j logs format..? And How..?
2. Are above stanza's are correct, can you pls verify once.

Kindly suggest and help to resolve this issue.

**Comment by vinzent** [comment] 2021-03-01 20:44
IMHO this is more a fluentd question and not a bugreport and not a enhancement request. I'd recommend to get in touch with the fluentd community.

https://www.fluentd.org/community

**Comment by jaypalpatil** [comment] 2021-03-02 07:47
I have already mounted the '/usr/local/tomcat/logs/*' directory in daemonset.yaml file. Take a look :

`
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-kubernetes-logging
  namespace: fluentd-amax
  labels:
    app: splunk-kubernetes-logging
    engine: fluentd
    version: 1.4.6
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: splunk-kubernetes-logging
  template:
    metadata:
      labels:
        app: splunk-kubernetes-logging
        version: 1.4.6
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '24231'
    spec:
      serviceAccountName: splunk-kubernetes-logging
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: splunk-fluentd-k8s-logs
        image: docker.io/splunk/fluentd-hec:1.2.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          privileged: false
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-logging
              key: splunk_hec_token
        - name: SSL_CERT_FILE
          value: "/fluentd/etc/splunk/hec_ca_file"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: "/var/log"
        - name: varapp
          mountPath: "/usr/local/tomcat/logs"
        - name: varlogdest
          mountPath: "/var/vcap/store/docker/docker/containers"
          readOnly: true
        - name: journallogpath
          mountPath: "/run/log/journal"
          readOnly: true
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: "/var/log"
      - name: varapp
        hostPath:
          path: "/usr/local/tomcat/logs"
      - name: varlogdest
        hostPath:
          path: "/var/vcap/store/docker/docker/containers"
      - name: journallogpath
        hostPath:
          path: "/run/log/journal"
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-logging
      - name: secrets
        secret:
          secretName: splunk-kubernetes-logging

`
**Can you pls review the above file once...**

Now I will make the other 2 suggested changes :

- tag tail.tomcat.*
- <filter tail.tomcat.usr.local.tomcat.logs.erefill_*.log>
 
Will let you the feedback on these changes. Thank you..!!

**Comment by rockb1017** [comment] 2021-03-02 21:13
but do you also have `/usr/local/tomcat/` path mounted to your tomcat pod? 
do you get any errors regarding tomcat log files on fluentd pod?

**Comment by harshit-splunk** [comment] 2021-12-16 07:04
Hey @jaypalpatil , were you able to get tocat logs in splunk? Please let us know.

**Comment by harshit-splunk** [comment] 2021-12-30 10:25
Closing the issue for now. Feel free to reopen or create a new one if needed.

**Closed by harshit-splunk** 2021-12-30 10:25 UTC
Labels: question
